### ISSUE TITLE
Restrict `treescope` default registration to specific types

### ISSUE THREAD

**Issue by gsarti** [google-deepmind/treescope#18]
For larger projects using `treescope`, it could be useful to allow for a restricted set of types to be passed to `register_as_default` to enable [overriding the IPython formatter](https://github.com/google-deepmind/treescope/blob/e52547b646e923cdc0cf6d6e263fd40b65848641/treescope/_internal/api/ipython_integration.py#L300C3-L300C30) only for specific types of interest. The default behavior of overriding `object` could be maintained.

e.g. `treescope.register_as_default(types=[nn.Module, MyType])`

Related questions:
- Is there a simple way to revert `treescope.register_as_default` to the default IPython behavior programmatically? Something like `treescope.unregister_as_default` could be useful outside of notebook usage.
- If a third-party type (e.g. `rich.jupyter.JupyterRenderable` in my case) doesn't implement `_repr_html_`, is there a way to tell `treescope` to let it render normally instead of taking over?

**Comment by danieldjohnson** [comment]
Hm, I wonder if this use case is common enough to warrant the complexity. If you want to customize exactly which types use Treescope, I think you can directly set this on the IPython formatter using `IPython.get_ipython().display_formatter.formatters["text/html"].for_type(SomeType, formatter_fn)` or by defining `_repr_html_` on the object, and having it use Treescope to render the object to HTML. Would that work?

For your other questions:

- > Is there a simple way to revert `treescope.register_as_default` to the default IPython behavior programmatically? 

  No, right now there isn't an easy way to revert the behavior, since the state is really controlled by the IPython formatter. You should be able to *mostly* disable it by doing
  ```python
  del IPython.get_ipython().display_formatter.formatters["text/html"].type_printers[object]
  ```
  although `register_as_default` also disables some other things that are tricky to re-enable in a uniform way.

- > If a third-party type (e.g. `rich.jupyter.JupyterRenderable` in my case) doesn't implement `_repr_html_`, is there a way to tell treescope to let it render normally instead of taking over?

  Not right now, but this could probably be improved! The intent was for treescope to disable itself if the object is already a Jupyter-renderable object, but I think the detection logic isn't perfect right now. Looks like `JupyterRenderable` implements `_repr_mimebundle_` which Treescope isn't currently checking. (I'm not sure if IPython provides a mechanism for determining whether a type has a different formatter registered.)

**Comment by gsarti** [comment]
Thanks for the quick answer! For now I settled on a context manager that looks like this, in case this could be helpful to someone:

```python
def treescope_ignore(f: Callable[..., Any]) -> Callable[..., Any]:
    @wraps(f)
    def treescope_unhooked_wrapper(self, *args, **kwargs):
        if isnotebook():
            # Unhook the treescope visualization to allow `rich.jupyter.JupyterRenderable` to render correctly
            import IPython
            del IPython.get_ipython().display_formatter.formatters["text/html"].type_printers[object]
        out = f(self, *args, **kwargs)
        if isnotebook():
            # Re-hook the treescope visualization
            ts.register_as_default()
        return out

    return treescope_unhooked_wrapper
```
