### ISSUE TITLE
Converting jupyter notebooks with treescope renderings to html files

### ISSUE THREAD

**Issue by amifalk** [google-deepmind/treescope#4]
By default, treescope visualizations in .ipynb files do not render at all when said notebooks are converted to html files. I see in the treescope docs that there's some javascript that's inserted into cell outputs to ensure it works properly with the docs, but its embedded in the Sphinx machinery. Is there a simple solution to get treescope visualizations to render without having to go through Sphinx?

**Comment by amifalk** [comment]
Closing this as html conversion works when using `treescope.basic_interactive_setup()`, just not with the  penzai alias `pz.ts.basic_interactive_setup()`

**Comment by danieldjohnson** [comment]
Hm, this still shouldn't be happening even through the Penzai alias.

What version of Penzai do you have installed? This sounds like could be caused by a rendering bug that was introduced in Penzai 0.1.4 and fixed in Penzai 0.1.5.

(Note that before Penzai 0.2.0, Treescope was part of Penzai, so Penzai 0.1.x has its own copy of Treescope and isn't compatible with the separate `treescope` package. On the other hand, Penzai 0.2.0 uses the separate `treescope` package directly for its pretty-printing, so there should be no rendering differences between Treescope 0.1.0 and Penzai 0.2.0.)

**Comment by amifalk** [comment]
Yep - there must have been a version mismatch! This works no matter how you import with Penzai 0.2.0, but fails with Penzai 0.1.4.
